name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: 'Tagged Release'
    runs-on: 'ubuntu-latest'

    steps:
      - uses: actions/checkout@v4
      - uses: wyvox/action-setup-pnpm@v3
        with:
          node-registry-url: "https://registry.npmjs.org"
      - run: pnpm build
      - run: pnpm -r publish --access public
